#!/bin/sh

set -eu

if ! cargo xtask gen-man
then
  echo "Task 'gen-man' failed"
  exit 1
fi

if ! cargo xtask gen-comp
then
  echo "Task 'gen-comp' failed"
  exit 1
fi

if ! git diff --quiet extra/completions
then
  echo "Shell completions changed, please add the changes via \"git add extra/completions/*\""
  exit 1
fi

if ! git diff --quiet extra/man
then
  echo "Man pages changed, please add the changes via \"git add extra/man/*\""
  exit 1
fi

exit 0