[workspace]
members = ["rust/*", "web", "."]
resolver = "2"

[workspace.package]
# Currently we version stackablectl separately from the other tools in this repo,
# as we want to already ship a binary to enable easy testing.
# We need to decide on a versioning strategy (e.g. version stackable-cokpit
# using semver or use SDP releases) in the future. Once we have the decision
# we can consolidate the stackablectl version.
version = "0.0.0-dev"
authors = ["Stackable GmbH <info@stackable.tech>"]
license = "OSL-3.0"
# We can use 2024 as soon as https://github.com/rust-lang/cc-rs/issues/1409 is
# fixed / supported.
edition = "2021"
repository = "https://github.com/stackabletech/stackable-cockpit/"

[workspace.dependencies]
async-trait = "0.1"
axum = { version = "0.7", features = ["http2"] }
axum-extra = { version = "0.9", features = ["typed-header"] }
bcrypt = "0.15"
bindgen = "0.70.1"
cc = "1.0.106"
clap = { version = "4.5", features = ["derive", "env"] }
clap_complete = "4.5"
clap_complete_nushell = "4.5"
comfy-table = { version = "7.1", features = ["custom_styling"] }
directories = "5.0"
dotenvy = "0.15"
futures = "0.3"
indexmap = { version = "2.2", features = ["serde"] }
indicatif = "0.17.11"
k8s-openapi = { version = "0.24", default-features = false, features = ["v1_32"] }
kube = { version = "0.99", default-features = false, features = ["client", "rustls-tls", "ws", "socks5", "http-proxy"] }
lazy_static = "1.5"
libc = "0.2"
once_cell = "1.19"
phf = "0.11"
phf_codegen = "0.11"
rand = "0.8"
regex = "1.10"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-native-roots"] }
rstest = "0.22"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.10"
snafu = { version = "0.8", features = ["futures"] }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "stackable-operator-0.92.0", default-features = false }
tera = "1.20"
termion = "4.0"
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "fs", "process", "io-std"] }
tower-http = { version = "0.5", features = ["validate-request"] }
tracing = "0.1"
tracing-indicatif = "0.3.9"
tracing-subscriber = "0.3"
url = "2.5"
urlencoding = "2.1.3"
utoipa = { version = "4.2", features = ["indexmap"] }
utoipa-swagger-ui = { version = "7.1", features = ["axum"] }
uuid = { version = "1.10", features = ["v4"] }
which = "6.0"

# [patch."https://github.com/stackabletech/operator-rs.git"]
# stackable-operator = { git = "https://github.com/stackabletech//operator-rs.git", branch = "main" }

[profile.release.package.stackablectl]
# opt-level = "z" # We don't use that as the binary saving is not *that* big (think of 1MB) and it's not worth it risiking performance for this
strip = true
# Cannot use because of https://github.com/rust-lang/cargo/issues/8264#issuecomment-751931213
# lto = true
codegen-units = 1
# Cannot use because of https://github.com/rust-lang/cargo/issues/8264#issuecomment-751931213
# panic = "abort"
