/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/demos": {
    /**
     * Retrieves all demos.
     * @description Retrieves all demos.
     */
    get: operations["get_demos"];
  };
  "/demos/{name}": {
    /**
     * Retrieves one demo identified by `name`.
     * @description Retrieves one demo identified by `name`.
     */
    get: operations["get_demo"];
  };
  "/login": {
    post: operations["log_in"];
  };
  "/ping": {
    get: operations["ping"];
  };
  "/releases": {
    /**
     * Retrieves all releases.
     * @description Retrieves all releases.
     */
    get: operations["get_releases"];
  };
  "/releases/{name}": {
    /**
     * Retrieves one release identified by `name`.
     * @description Retrieves one release identified by `name`.
     */
    get: operations["get_release"];
  };
  "/stacklets": {
    /**
     * Retrieves all stacklets.
     * @description Retrieves all stacklets.
     */
    get: operations["get_stacklets"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description This struct describes a demo with the v2 spec */
    DemoSpecV2: {
      /** @description A short description of the demo */
      description: string;
      /** @description An optional link to a documentation page */
      documentation?: string | null;
      /** @description A variable number of labels (tags) */
      labels?: string[];
      /** @description A variable number of Helm or YAML manifests */
      manifests?: components["schemas"]["ManifestSpec"][];
      /** @description A variable number of supported parameters */
      parameters?: components["schemas"]["Parameter"][];
      resourceRequests?: components["schemas"]["ResourceRequests"] | null;
      /** @description The name of the underlying stack */
      stackableStack: string;
      /**
       * @description Supported namespaces this demo can run in. An empty list indicates that
       * the demo can run in any namespace.
       */
      supportedNamespaces?: string[];
    };
    DisplayCondition: {
      condition: string;
      is_good?: boolean | null;
      message?: string | null;
    };
    ManifestSpec: OneOf<[{
      helmChart: string;
    }, {
      plainYaml: string;
    }]>;
    ObjectMeta: {
      name: string;
      namespace: string;
    };
    /** @description Parameter descibes a common parameter format. This format is used in demo and stack definitions */
    Parameter: {
      /** @description Parameter default value */
      default: string;
      /** @description Parameter description */
      description: string;
      /** @description Parameter name */
      name: string;
    };
    ReleaseSpec: {
      /** @description A short description of this release */
      description: string;
      /** @description List of products and their version in this release */
      products: {
        [key: string]: components["schemas"]["ProductSpec"];
      };
      /** @description Date this released was released */
      releaseDate: string;
    };
    /**
     * @description Demos and stacks can define how much cluster resources they need to run
     * via their definition. The struct [`ResourceRequests`] contains information
     * how many CPU cores and how much memory and disk space are required to run
     * the demo/stack.
     */
    ResourceRequests: {
      cpu: string;
      memory: string;
      pvc: string;
    };
    Session: {
      sessionToken: components["schemas"]["SessionToken"];
    };
    SessionToken: string;
    Stacklet: {
      /** @description Multiple cluster conditions. */
      conditions: components["schemas"]["DisplayCondition"][];
      credentials?: components["schemas"]["Credentials"] | null;
      /**
       * @description Endpoint addresses the product is reachable at.
       * The key is the service name (e.g. `web-ui`), the value is the URL.
       */
      endpoints: {
        [key: string]: string;
      };
      /** @description Name of the stacklet. */
      name: string;
      /** @description Some CRDs are cluster scoped. */
      namespace?: string | null;
      /** @description Name of the product. */
      product: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /**
   * Retrieves all demos.
   * @description Retrieves all demos.
   */
  get_demos: {
    responses: {
      /** @description Retrieving a list of demos succeeded */
      200: {
        content: {
          "application/json": components["schemas"]["DemoSpecV2"][];
        };
      };
      /** @description Retrieving a list of demos failed */
      404: {
        content: never;
      };
    };
  };
  /**
   * Retrieves one demo identified by `name`.
   * @description Retrieves one demo identified by `name`.
   */
  get_demo: {
    responses: {
      /** @description Retrieving the demo with 'name' succeeded */
      200: {
        content: {
          "application/json": components["schemas"]["DemoSpecV2"];
        };
      };
      /** @description Retrieving the demo with 'name' failed */
      404: {
        content: never;
      };
    };
  };
  log_in: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      401: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
  ping: {
    responses: {
      200: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
  /**
   * Retrieves all releases.
   * @description Retrieves all releases.
   */
  get_releases: {
    responses: {
      /** @description Retrieving a list of releases succeeded */
      200: {
        content: {
          "application/json": components["schemas"]["ReleaseSpec"][];
        };
      };
      /** @description Retrieving a list of releases failed */
      404: {
        content: never;
      };
    };
  };
  /**
   * Retrieves one release identified by `name`.
   * @description Retrieves one release identified by `name`.
   */
  get_release: {
    responses: {
    };
  };
  /**
   * Retrieves all stacklets.
   * @description Retrieves all stacklets.
   */
  get_stacklets: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Stacklet"][];
        };
      };
    };
  };
}
