.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH stackablectl 1  "stackablectl 24.11.3" 
.SH NAME
stackablectl \- Command line tool to interact with the Stackable Data Platform
.SH SYNOPSIS
\fBstackablectl\fR [\fB\-l\fR|\fB\-\-log\-level\fR] [\fB\-\-no\-cache\fR] [\fB\-d\fR|\fB\-\-demo\-file\fR] [\fB\-s\fR|\fB\-\-stack\-file\fR] [\fB\-r\fR|\fB\-\-release\-file\fR] [\fB\-\-helm\-repo\-stable\fR] [\fB\-\-helm\-repo\-test\fR] [\fB\-\-helm\-repo\-dev\fR] [\fB\-\-chart\-source\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Command line tool to interact with the Stackable Data Platform
.SH OPTIONS
.TP
\fB\-l\fR, \fB\-\-log\-level\fR=\fILOG_LEVEL\fR
Log level this application uses
.TP
\fB\-\-no\-cache\fR
Do not cache the remote (default) demo, stack and release files

Cached files are saved at \*(Aq$XDG_CACHE_HOME/stackablectl\*(Aq, which is usually
\*(Aq$HOME/.cache/stackablectl\*(Aq when not explicitly set.
.TP
\fB\-d\fR, \fB\-\-demo\-file\fR=\fIDEMO_FILE\fR
Provide one or more additional (custom) demo file(s)

Demos are loaded in the following order: Remote (default) demo file, custom
demo files provided via the \*(AqSTACKABLE_DEMO_FILES\*(Aq environment variable, and
lastly demo files provided via the \*(Aq\-d/\-\-demo\-file\*(Aq argument(s). If there are
demos with the same name, the last demo definition will be used.

Use "stackablectl [OPTIONS] <COMMAND> \-d path/to/demos1.yaml \-d path/to/demos2.yaml"
to provide multiple additional demo files.
.TP
\fB\-s\fR, \fB\-\-stack\-file\fR=\fISTACK_FILE\fR
Provide one or more additional (custom) stack file(s)

Stacks are loaded in the following order: Remote (default) stack file, custom
stack files provided via the \*(AqSTACKABLE_STACK_FILES\*(Aq environment variable, and
lastly demo files provided via the \*(Aq\-s/\-\-stack\-file\*(Aq argument(s). If there are
stacks with the same name, the last stack definition will be used.

Use "stackablectl [OPTIONS] <COMMAND> \-s path/to/stacks1.yaml \-s path/to/stacks2.yaml"
to provide multiple additional stack files.
.TP
\fB\-r\fR, \fB\-\-release\-file\fR=\fIRELEASE_FILE\fR
Provide one or more additional (custom) release file(s)

Releases are loaded in the following order: Remote (default) release file,
custom release files provided via the \*(AqSTACKABLE_RELEASE_FILES\*(Aq environment
variable, and lastly release files provided via the \*(Aq\-r/\-\-release\-file\*(Aq
argument(s). If there are releases with the same name, the last release
definition will be used.

Use "stackablectl [OPTIONS] <COMMAND> \-r path/to/releases1.yaml \-r path/to/releases2.yaml"
to provide multiple additional release files.
.TP
\fB\-\-helm\-repo\-stable\fR=\fIURL\fR [default: https://repo.stackable.tech/repository/helm\-stable/]
Provide a custom Helm stable repository URL
.TP
\fB\-\-helm\-repo\-test\fR=\fIURL\fR [default: https://repo.stackable.tech/repository/helm\-test/]
Provide a custom Helm test repository URL
.TP
\fB\-\-helm\-repo\-dev\fR=\fIURL\fR [default: https://repo.stackable.tech/repository/helm\-dev/]
Provide a custom Helm dev repository URL
.TP
\fB\-\-chart\-source\fR=\fICHART_SOURCE\fR [default: oci]
Source the charts from either a OCI registry or from index.yaml\-based repositories.
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
oci: OCI registry
.IP \(bu 2
repo: index.yaml\-based repositories: resolution (dev, test, stable) is based on the version and thus will be operator\-specific
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
stackablectl\-operator(1)
Interact with single operator instead of the full platform
.TP
stackablectl\-release(1)
Interact with all operators of the platform which are released together
.TP
stackablectl\-stack(1)
Interact with stacks, which are ready\-to\-use product combinations
.TP
stackablectl\-stacklet(1)
Interact with deployed stacklets, which are bundles of resources and containers required to run the product
.TP
stackablectl\-demo(1)
Interact with demos, which are end\-to\-end usage demonstrations of the Stackable data platform
.TP
stackablectl\-completions(1)
Generate shell completions for this tool
.TP
stackablectl\-cache(1)
Interact with locally cached files
.TP
stackablectl\-experimental\-debug(1)
EXPERIMENTAL: Launch a debug container for a Pod
.TP
stackablectl\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v24.11.3
.SH AUTHORS
Stackable GmbH <info@stackable.tech>
