= stackablectl cache

The `cache` command let's you interact with locally cached files. The `stackablectl` tool retrieves release, demo, and
stack definitions from a dedicated GitHub repository. It additionally retrieves Helm / YAML manifests from various other
sources. These files are downloaded once and then cached for one hour. In this time period, the files are not downloaded
again, but instead the locally cached (stored on disk) files are used. Users can opt out of caching by providing the
`--no-cache` flag.

== General Usage

include::management:stackablectl:partial$commands/cache.adoc[]

== Listing Cached Files

To list currently cached files, use `stackablectl cache list`:

[source,console]
----
$ stackablectl cache list
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────┐
│ FILE                                                                                                           ┆ LAST SYNC      │
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪════════════════╡
│ $HOME/.cache/stackablectl/https---raw-githubusercontent-com-stackabletech-stackablectl-main-stacks-stacks-v2-y ┆ 3 seconds ago  │
│ aml-17447ade21bb02fe827b33ef32404e7cb3866ee169837dead6dfdcd7f7241e07                                           ┆                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ $HOME/.cache/stackablectl/https---raw-githubusercontent-com-stackabletech-stackablectl-main-demos-demos-v2-yam ┆ 22 seconds ago │
│ l-a140c16c241efa6dbee780d48843a1975bd1069ee8dd8f936123ffb8ee700739                                             ┆                │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────┘
----

== Cleaning Cached Files

To clean currently cached files, use `stackablectl cache clean`. This will remove **all** cached files, regardless if
the files are expired. To only delete outdated files, add the `--outdated` flag.
