= stackablectl operator
:page-aliases: stackablectl::commands/operator.adoc

The `stackable operator` command allows the listing, installation and removal of Stackable operators. Operators manage
the individual data products of the Stackable Data Platform.

This command manages individual operators. It is intended for people with experience working on the Stackable Data
Platform. If you want an easy way to get started or don't know which products and versions to install, using the
xref:commands/release.adoc[`stackablectl release`] command is recommended. This command will install a bundle of
operators from an official Stackable release.

== General Usage

include::management:stackablectl:partial$commands/operator.adoc[]

== Listing Available Operators

To list the operators that are part of the Stackable Data Platform and their stable versions, run the following
command:

[source,console]
----
$ stackablectl operator list
┌────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────┐
│ #  ┆ OPERATOR  ┆ STABLE VERSIONS                                                                        │
╞════╪═══════════╪════════════════════════════════════════════════════════════════════════════════════════╡
│ 1  ┆ airflow   ┆ 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 23.1.0, 23.4.0, 23.4.1, 23.7.0               │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2  ┆ ...       ┆ ...                                                                                    │
├╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 15 ┆ zookeeper ┆ 0.10.0, 0.11.0, 0.12.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 23.1.0, 23.4.0, 23.4.1, 23.7.0     │
└────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────┘
----

This command only includes the stable versions of every operator for clarity. If you're interested in a particular
version of an operator, you can use the `describe` command to get more details for a specific operator as follows:

[source,console]
----
$ stackablectl operator describe airflow
 OPERATOR         airflow
 STABLE VERSIONS  0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 23.1.0, 23.4.0, 23.4.1, 23.7.0
 TEST VERSIONS    0.0.0-pr303, 0.0.0-pr304, 0.0.0-pr305, 0.0.0-pr307, 0.0.0-pr308, 0.0.0-pr310, 0.0.0-pr311, 0.0.0-pr312, 0.0.0-pr314, 0.0.0-pr315,
                  0.0.0-pr316, 0.0.0-pr317
 DEV VERSIONS     0.0.0-dev
----

== Installing Operators

If you want to access a Kubernetes cluster, make sure your https://kubernetes.io/docs/tasks/tools/#kubectl[`kubectl`]
Kubernetes client is configured to interact with the Kubernetes cluster. After that, run the following command, which
will install the operators in their latest nightly version - built from the main branch of the operators.

[source,console]
----
$ stackablectl operator install airflow commons secret
Installing 3 operators
Installed airflow operator
Installed commons operator
Installed secret operator
Installed 3 operators
----

If you don't have a Kubernetes cluster available, `stackablectl` can spin up a https://kind.sigs.k8s.io/[kind] or
https://minikube.sigs.k8s.io/docs/[minikube] Kubernetes cluster for you. Based on the type of local cluster you want to
use, ensure you have either `kind` or `minikube` installed on your system. See
xref:commands/demo.adoc#_using_a_local_kubernetes_cluster[here] for more information.

With this command, we installed the operator for Apache Airflow and two operators needed internally by the Stackable
Data Platform (commons and secret). As we didn't specify a specific version to install, the operators were installed in
the latest nightly version - built from the main branch of the operators. If you want to install a specific version, you
can add the version to each operator to install as follows:

[source,console]
----
$ stackablectl operator install airflow=23.7 commons=23.7 secret=23.7
Installing 3 operators
Installed airflow=23.7 operator
Installed commons=23.7 operator
Installed secret=23.7 operator
Installed 3 operators
----

As you can see, the three operators were installed in the requested version.

Remember: If you want to install a recommended and tested set of operator versions, look at the
xref:commands/release.adoc[`stackablectl release`] command.

== Listing Installed Operators

After installing some operators, you can list which operators are installed in your Kubernetes cluster:

[source,console]
----
$ stackablectl operator installed
┌──────────────────┬─────────┬─────────────────────┬──────────┬──────────────────────────────────────────┐
│ OPERATOR         ┆ VERSION ┆ NAMESPACE           ┆ STATUS   ┆ LAST UPDATED                             │
╞══════════════════╪═════════╪═════════════════════╪══════════╪══════════════════════════════════════════╡
│ airflow-operator ┆ 23.7.0  ┆ stackable-operators ┆ deployed ┆ 2023-08-23 17:33:01.509777626 +0200 CEST │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ commons-operator ┆ 23.7.0  ┆ stackable-operators ┆ deployed ┆ 2023-08-23 17:33:04.012698515 +0200 CEST │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ secret-operator  ┆ 23.7.0  ┆ stackable-operators ┆ deployed ┆ 2023-08-23 17:33:06.328410802 +0200 CEST │
└──────────────────┴─────────┴─────────────────────┴──────────┴──────────────────────────────────────────┘
----

== Uninstalling Operators

You can use the `stackablectl operator uninstall` command to uninstall the operators again.

[source,console]
----
$ stackablectl operator uninstall airflow commons secret
The release airflow-operator was successfully uninstalled.
The release commons-operator was successfully uninstalled.
The release secret-operator was successfully uninstalled.
Uninstalled 3 operators
----
