complete -c stackablectl -n "__fish_use_subcommand" -s l -l log-level -d 'Log level this application uses' -r
complete -c stackablectl -n "__fish_use_subcommand" -s n -l operator-namespace -d 'Namespace in the cluster used to deploy the products and operators' -r
complete -c stackablectl -n "__fish_use_subcommand" -s d -l demo-file -d 'Provide one or more additional (custom) demo file(s)' -r -F
complete -c stackablectl -n "__fish_use_subcommand" -s s -l stack-file -d 'Provide one or more additional (custom) stack file(s)' -r -F
complete -c stackablectl -n "__fish_use_subcommand" -s r -l release-file -d 'Provide one or more additional (custom) release file(s)' -r -F
complete -c stackablectl -n "__fish_use_subcommand" -l helm-repo-stable -d 'Provide a custom Helm stable repository URL' -r -f
complete -c stackablectl -n "__fish_use_subcommand" -l helm-repo-test -d 'Provide a custom Helm test repository URL' -r -f
complete -c stackablectl -n "__fish_use_subcommand" -l helm-repo-dev -d 'Provide a custom Helm dev repository URL' -r -f
complete -c stackablectl -n "__fish_use_subcommand" -l no-cache -d 'Do not cache the remote (default) demo, stack and release files'
complete -c stackablectl -n "__fish_use_subcommand" -l offline -d 'Do not request any remote files via the network'
complete -c stackablectl -n "__fish_use_subcommand" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_use_subcommand" -f -a "operator" -d 'Interact with single operator instead of the full platform'
complete -c stackablectl -n "__fish_use_subcommand" -f -a "release" -d 'Interact with all operators of the platform which are released together'
complete -c stackablectl -n "__fish_use_subcommand" -f -a "stack" -d 'Interact with stacks, which are ready-to-use product combinations'
complete -c stackablectl -n "__fish_use_subcommand" -f -a "stacklets" -d 'Interact with deployed stacklets, which are bundles of resources and containers required to run the product'
complete -c stackablectl -n "__fish_use_subcommand" -f -a "demo" -d 'Interact with demos, which are end-to-end usage demonstrations of the Stackable data platform'
complete -c stackablectl -n "__fish_use_subcommand" -f -a "completions" -d 'Generate shell completions for this tool'
complete -c stackablectl -n "__fish_use_subcommand" -f -a "cache" -d 'Interact with locally cached files'
complete -c stackablectl -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available (or installed) operators'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "describe" -d 'Print out detailed operator information'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install one or more operators'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "uninstall" -d 'Uninstall one or more operators'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "installed" -d 'List installed operator (same as list -i)'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from list" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from describe" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from describe" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from describe" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from install" -s c -l cluster -d 'Type of local cluster to use for testing' -r -f -a "{kind	Use a kind cluster\, see \'https://docs.stackable.tech/home/getting_started.html#_installing_kubernetes_using_kind\',minikube	Use a minikube cluster (CURRENTLY UNSUPPORTED)}"
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from install" -l cluster-name -d 'Name of the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from install" -l cluster-nodes -d 'Number of total nodes in the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from install" -l cluster-cp-nodes -d 'Number of control plane nodes in the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from install" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from uninstall" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from uninstall" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from installed" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from installed" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from installed" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available (or installed) operators'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "describe" -d 'Print out detailed operator information'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install one or more operators'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "uninstall" -d 'Uninstall one or more operators'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "installed" -d 'List installed operator (same as list -i)'
complete -c stackablectl -n "__fish_seen_subcommand_from operator; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available releases'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "describe" -d 'Print out detailed release information'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install a specific release'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "uninstall" -d 'Uninstall a release'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from list" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from describe" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from describe" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from describe" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from install" -s i -l include -d 'Whitelist of product operators to install' -r
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from install" -s e -l exclude -d 'Blacklist of product operators to install' -r
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from install" -s c -l cluster -d 'Type of local cluster to use for testing' -r -f -a "{kind	Use a kind cluster\, see \'https://docs.stackable.tech/home/getting_started.html#_installing_kubernetes_using_kind\',minikube	Use a minikube cluster (CURRENTLY UNSUPPORTED)}"
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from install" -l cluster-name -d 'Name of the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from install" -l cluster-nodes -d 'Number of total nodes in the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from install" -l cluster-cp-nodes -d 'Number of control plane nodes in the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from install" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from uninstall" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from uninstall" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available releases'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "describe" -d 'Print out detailed release information'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install a specific release'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "uninstall" -d 'Uninstall a release'
complete -c stackablectl -n "__fish_seen_subcommand_from release; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available stacks'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "describe" -d 'Describe a specific stack'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install a specific stack'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from list" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from describe" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from describe" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from describe" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from install" -s s -l stack-parameters -d 'List of parameters to use when installing the stack' -r
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from install" -s p -l parameters -d 'List of parameters to use when installing the stack' -r
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from install" -s c -l cluster -d 'Type of local cluster to use for testing' -r -f -a "{kind	Use a kind cluster\, see \'https://docs.stackable.tech/home/getting_started.html#_installing_kubernetes_using_kind\',minikube	Use a minikube cluster (CURRENTLY UNSUPPORTED)}"
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from install" -l cluster-name -d 'Name of the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from install" -l cluster-nodes -d 'Number of total nodes in the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from install" -l cluster-cp-nodes -d 'Number of control plane nodes in the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from install" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available stacks'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "describe" -d 'Describe a specific stack'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install a specific stack'
complete -c stackablectl -n "__fish_seen_subcommand_from stack; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List deployed services'
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and __fish_seen_subcommand_from list" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and __fish_seen_subcommand_from list" -s a -l all-namespaces -d 'Will display services of all namespaces, not only the current one'
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and __fish_seen_subcommand_from list" -s c -l color -d 'Controls if the output will use color. This only applies to the output type \'plain\''
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List deployed services'
complete -c stackablectl -n "__fish_seen_subcommand_from stacklets; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available demos'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "describe" -d 'Print out detailed demo information'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install a specific demo'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "uninstall"
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from list" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from describe" -s o -l output -r -f -a "{plain	Print output formatted as plain text,json	Print output formatted as JSON,yaml	Print output formatted as YAML}"
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from describe" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from describe" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from install" -s s -l stack-parameters -d 'List of parameters to use when installing the stack' -r
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from install" -s p -l parameters -d 'List of parameters to use when installing the demo' -r
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from install" -s c -l cluster -d 'Type of local cluster to use for testing' -r -f -a "{kind	Use a kind cluster\, see \'https://docs.stackable.tech/home/getting_started.html#_installing_kubernetes_using_kind\',minikube	Use a minikube cluster (CURRENTLY UNSUPPORTED)}"
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from install" -l cluster-name -d 'Name of the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from install" -l cluster-nodes -d 'Number of total nodes in the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from install" -l cluster-cp-nodes -d 'Number of control plane nodes in the local cluster' -r
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from install" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from uninstall" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from uninstall" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available demos'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "describe" -d 'Print out detailed demo information'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install a specific demo'
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "uninstall"
complete -c stackablectl -n "__fish_seen_subcommand_from demo; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -f -a "bash" -d 'Generate shell completions for Bash'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -f -a "fish" -d 'Generate shell completions for Fish'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -f -a "zsh" -d 'Generate shell completions for ZSH'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from bash" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from bash" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from fish" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from fish" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from zsh" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from zsh" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -f -a "bash" -d 'Generate shell completions for Bash'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -f -a "fish" -d 'Generate shell completions for Fish'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -f -a "zsh" -d 'Generate shell completions for ZSH'
complete -c stackablectl -n "__fish_seen_subcommand_from completions; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List cached files'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "clean" -d 'Clean cached files'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and __fish_seen_subcommand_from clean" -s h -l help -d 'Print help'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and __fish_seen_subcommand_from clean" -s V -l version -d 'Print version'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List cached files'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "clean" -d 'Clean cached files'
complete -c stackablectl -n "__fish_seen_subcommand_from cache; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "operator" -d 'Interact with single operator instead of the full platform'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "release" -d 'Interact with all operators of the platform which are released together'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "stack" -d 'Interact with stacks, which are ready-to-use product combinations'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "stacklets" -d 'Interact with deployed stacklets, which are bundles of resources and containers required to run the product'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "demo" -d 'Interact with demos, which are end-to-end usage demonstrations of the Stackable data platform'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "completions" -d 'Generate shell completions for this tool'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "cache" -d 'Interact with locally cached files'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed" -f -a "list" -d 'List available (or installed) operators'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed" -f -a "describe" -d 'Print out detailed operator information'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed" -f -a "install" -d 'Install one or more operators'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed" -f -a "uninstall" -d 'Uninstall one or more operators'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from operator; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from installed" -f -a "installed" -d 'List installed operator (same as list -i)'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall" -f -a "list" -d 'List available releases'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall" -f -a "describe" -d 'Print out detailed release information'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall" -f -a "install" -d 'Install a specific release'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from release; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall" -f -a "uninstall" -d 'Uninstall a release'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install" -f -a "list" -d 'List available stacks'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install" -f -a "describe" -d 'Describe a specific stack'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from stack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install" -f -a "install" -d 'Install a specific stack'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from stacklets; and not __fish_seen_subcommand_from list" -f -a "list" -d 'List deployed services'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall" -f -a "list" -d 'List available demos'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall" -f -a "describe" -d 'Print out detailed demo information'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall" -f -a "install" -d 'Install a specific demo'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from describe; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall" -f -a "uninstall"
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh" -f -a "bash" -d 'Generate shell completions for Bash'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh" -f -a "fish" -d 'Generate shell completions for Fish'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash; and not __fish_seen_subcommand_from fish; and not __fish_seen_subcommand_from zsh" -f -a "zsh" -d 'Generate shell completions for ZSH'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean" -f -a "list" -d 'List cached files'
complete -c stackablectl -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from clean" -f -a "clean" -d 'Clean cached files'
