---
name: Pull Request Docs

on:
  pull_request:
    paths:
      - ".github/workflows/pr_docs.yml"
      - "docs/**"

jobs:
  general-checks:
    name: General Pull Request Checks
    uses: ./.github/workflows/pr_general.yml
